mean_GC_content: 0.41 # adjust based on your genome's mean GC content


variants:

  DEL:
    count: 100              
    distribution: "lognormal"
    parameters:
      mean_length: 5000      # Target mean length in bp
      sigma:             # Shape parameter for lognormal
      min_length: 50        # Hard cap: nothing smaller than 50bp
      max_length: 100000     # Hard cap: nothing larger than 10kb

  INS:
    count: 50
    distribution: "lognormal" 
    parameters:
      mean_length: 10000
      sigma: 
      min_length: 100
      max_length: 100000


  DUP:                                # tandem duplications
    count: 40               
    distribution: "lognormal"
    parameters:
      mean_length: 2000
      sigma: 200
      min_length: 50
      max_length: 5000
    copy_number:           
      min: 2
      max: 5
      weights: [0.7, 0.2, 0.05, 0.05] # Probability for CN=2, 3, 4, 5


  INV:
    count: 25
    distribution: "lognormal"   
    parameters:
      mean_length: 1500
      sigma: 
      min_length: 50
      max_length: 100000